language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

env:
  global:
    #TRAVIS_ACCESS_TOKEN
    secure: "fNNB939AoaPBnWt0NAXpkYcvb/E8wyQc6e/5L0q3l7Sk98fncvDXSMfAsT80zQaJUDjxGgUGOjfTAYYD4rLN/ljEwpkhPWsWxQxa9VRmlVNjratTKHKA1FXfzgelxXtJlbK7I4eNtBlhjvNo0e8kCFMWZos4VNSisLeVDSma1I5Ph/dJorXwnqc15LHh98EovtLoWYNcMDUlSQCa5tbQFq7pqLeZzdPNuHyzc2O6rdRG0j7yYVZpUYqBeQUf2AE0oLR850RJvr8bFZUpfwmHHoRcxm4fWVEJcH/qg0D3kwYNHVFVuRISUF1LWyujmQ46JHZD5ulU7HDXIdhph10X6hV6LTuZpfEbr2MPJPV5X7MRxf1JzUXiZji+kpXYDN2byr9gFUECMsnd8EJ42OX9mFB66SjIPMCO4pR6EuGUystrD1FtvPGbplWTn45MOZl9dQ8/anxER5dXrXGfvriiY4RfPQ3M73z2rTHPP75vv59xpGGwG4TifZQIwTS6vBxtftyh6vLtATLiz+wKdc2+WMap/gTRFB2jl4qfBzI/b9XMJikLneZ2k6+mSFACO4uYXEhEuZobjIlPu7xzeixX2m4uiEMb9Tt12syU+5hbGm5xMMRIQmc+SWAU2eiGlq1xfg18zSZdkL5hqX218T8veOXRLs2n4aPpjSleEalBufo="
install:
  - python setup.py install

script:
  - python setup.py test

jobs:
  include:
  - stage: trigger
    if: (NOT type IN (pull_request)) AND (branch = master)
    script: |
      #https://github.com/plume-lib/trigger-travis
      #echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST TRAVIS_ACCESS_TOKEN=$TRAVIS_ACCESS_TOKEN"
      curl -LO --retry 3 https://raw.githubusercontent.com/plume-lib/trigger-travis/master/trigger-travis.sh
      sh trigger-travis.sh --pro --branch master untangle waf $TRAVIS_ACCESS_TOKEN 

notifications:
  email: false
  slack:
    rooms:
      - secure: Anf4o5PUukbx0ZHTmtwIGcXDpYXBSq5UIir+jbMiaSuUpKGRh1U0NjkkwrTEE7qEYBmEJAafisEzlbEnBeTI8PPSVPBsBAFj2cZ5fYhHeZuBehE8ZN36gAVTteO5t5oSh3TtOnag2DtNZPomOD0LkHr/qN0Rr16t2nkDXYPOpFKnhDMh/SAjDWboZM9son6XJiI9TQxh25HS5i8LVfle4dGCobWXmlvu9JYoRhjiWz2any/HaYPJnCC5rd4GNLkuKIW4fYCu8QcIjiTrSSwYpTlkJwbm/VuV/6bVUXWIElovjv8BLLbe0uVd5nyoileChah6QDyivgWqFidYGUO4o4mE9AoUQpEYcRKZanMaRbCjDBuj5UU1gJ+6CFMLSB0xVoFiBvSEiXs9LEI72OBil2ASxsJzfwJy2iowlJQVnpJFoIgb74yPIjLcvFyOeoQfsqjWRpxqexECZjQDxCAcarqa7ifW/ZcIi2n9kvvvp7f1rF0Hu9a5R341p2EUQeKgYRTSmBk5P1Q4hxJ20Sj3NyitxS6wZvpiEAactrAFfLHGLCSxG6gjNiY71+1QzjsmPuMkQI9MSLUNGDeluuTi4RFaGeeuPyNGxGMxj01KOMhly1d+bBfqOXG6oo5U9fkMqwqI5IVMjlVpGbz9txrzTel6RMpbOGn2vZevvD71bv8=
    on_success: change
    on_failure: always
