sudo: required

git:
  depth: false

services:
- docker

env:
  global:
    # DOCKER_PASSWORD
    - secure: "VKT3s497D4hGozTr1Yk9V5wZZd4Xi4vriSjNe3o1otxwOY8YIcVegcQSdr0i9D0T/imiROmQ2bxlM6spdqmjNTVj7q9AHGjtKg/9lWHF8swIL/3cBII1wkR4GLF4GEKRjlsMz4kWxzrZ+7GGzZ967zSm1T5Kr7Xn+PSUoiyLJcqJsubaEpsxf+0GrPV2RseKDTK5n4kwOF/8Ax28rJ9Wy0FpB8Me3A3dmqAp18o37SDpHOtr9pwLQWVqOXlhOn1J7oYB0FXlvCsti4jY0YkKiD9dLU9O06XkbYLGONh/GG8OboudV6rQKD1EmwBmn/I5P6mWW79aH4JnLAx8C/zOBkKm5CsWGlQ0Jj0u3lsjZ0M0k+1CxB5+VR29tDoeY1+ex+iZJdghrI7btoFsoOd6qqj7MKk/TYcZ5nj9S/TRHqbNTXncw0at3U+wjbkZHDvTGljI5EIDRBttM+CjczNXd/Y0AUlRLuwkFSr7M0jlDZxwlWAQvMAzKJWYoBwIlLO826dIzzRv94TCfidAxpQkCedhC1846NM4i1nW/3LwNTnAXBJVTYz/GqYemZ3YbbCDf7/tEGffkglLxKGEso69Sh2F48cVqAffQWBSsySDUhPJX+2Cjt5TWpTKMcuR2B99pEJei98gvmNdC4IWdu4AlcyOr7smgK828buk/Jl/Jzg="
    - DOCKER_USERNAME: untangleengineering
      SSH_KEY: /tmp/travis-buildbot.rsa
      PACKAGE_SERVER_IP: 50.211.244.129
      PKGTOOLS_COMMIT: origin/${TRAVIS_BRANCH}
      UPLOAD: scp
  jobs:
    - REPOSITORY: bullseye
      ARCHITECTURE: amd64
    - REPOSITORY: bullseye
      ARCHITECTURE: arm64

before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker pull untangleinc/ngfw:${REPOSITORY}-build-multiarch
- openssl aes-256-cbc -K $encrypted_4573965c4e34_key -iv $encrypted_4573965c4e34_iv -in .travis/buildbot.rsa.enc -out ${SSH_KEY} -d
- chmod 600 ${SSH_KEY}

script:
- docker-compose -f docker-compose.build.yml run pkgtools
- docker-compose -f docker-compose.build.yml run build

notifications:
  email: false
  slack:
    rooms:
      - secure: XzWyKqltaDMHYT5QevjL/uooNeLn3DBDru25wLTj1GzfRr25i+lVB+FvuWI6F3KcaKyNu0vNpP1N398KO/V45oYkUxc4rj7iS3yRvGcfedxtJDSSLO2BPR/iaotVnUqi+qnYSnEHa5pqGWC5OUVonN5+Sy9qqP5BLRbxN+SG9L5jBmzK86P/lY2ESmhOI/U4KiLdBxCNiQK/kxcpiCyEz4xZVwZgqxamRDHvVJDV7CNCZxu3qbUD9eC/gJ9RBscF0TCprdoK3c8DM4V2YNUtrbnn0yKV26gmk+ZevnQQYSXbtRq+oHIUcYJUzmIyhh0lZFD88kNAlQGdieuHuWP3toq5qORRiKx6xhncmERBWnX/lEybmkLjGGP/evm7X9Ct48iVAqmBnsTKlr3nab32O3iggtExVW4oqbP8nlYSoM/NV75gbos0J5IFRzD8rtfweMKP2nrNQLjsZrRufwaNmuWJyYdTLSRWrSRRtJhuU4aYEAHPO3FIfBrLY6Fh5Q09NHfh7YqkDrA1nVF0I4NFuMZt3ASbtC4F1cU5CpYIMgeJZs7p45BFA5efVwuWS0K2upZqXPqUN12BlbbaICo6CHsA0dfIDFVpJ/1bumSyxjKQiZe9pw9qnk4XdrNKvahYudB/VqXZAjrZcrRuFeG0uxckhJtK4nhbfccvpWES6VE=
    on_success: change
    on_failure: always
